certificatesResolvers:
  letsencrypt:
    acme:
      email: ${acme_email}
      storage: /data/acme.json
      caServer: https://acme-v02.api.letsencrypt.org/directory
      # caServer: https://acme-staging-v02.api.letsencrypt.org/directory
      dnsChallenge:
        provider: cloudflare
