apiVersion: v1
kind: Endpoints
metadata:
  name: plex
subsets:
  - addresses:
    - ip: {{ .Values.endpoint.ip }}
    ports:
    - name: web
      protocol: TCP
      port: {{ .Values.endpoint.port }}
