apiVersion: v1
kind: Service
metadata:
  name: plex
spec:
  ports:
  - name: web
    protocol: TCP
    port: {{ .Values.service.port }}
    targetPort: {{ .Values.service.targetPort }}
  clusterIP: None
