apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
  labels:
    app: postgres
spec:
  replicas: {{ .Values.deployment.replicas }}
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
      - name: postgres
        image: pgvector/pgvector:pg18
        ports:
        - name: db
          containerPort: {{ .Values.deployment.containerPort }}
          protocol: TCP
        env:
        {{- range $key, $value := .Values.env }}
        - name: {{ $key }}
          value: {{ $value | quote }}
        {{- end }}
        envFrom:
        - secretRef:
            name: postgres
        volumeMounts:
        - name: postgres-data
          mountPath: /var/lib/postgresql/18/docker
      volumes:
      - name: postgres-data
        hostPath:
          path: {{ .Values.volumes.data.hostPath }}
          type: DirectoryOrCreate
