apiVersion: v1
kind: Secret
metadata:
  name: postgres
type: Opaque
data:
  POSTGRES_USER: {{ .Values.secrets.username | b64enc | quote }}
  POSTGRES_PASSWORD: {{ .Values.secrets.password | b64enc | quote }}
