apiVersion: v1
kind: Service
metadata:
  name: postgres
  labels:
    app: postgres
spec:
  type: {{ .Values.service.type }}
  selector:
    app: postgres
  ports:
    - name: db
      protocol: TCP
      port: {{ .Values.service.port }}
      targetPort: db
