apiVersion: v1
kind: Service
metadata:
  name: pocket-id
spec:
  type: {{ .Values.service.type }}
  selector:
    app: pocket-id
  ports:
    - name: web
      protocol: TCP
      port: {{ .Values.service.port }}
      targetPort: web
