---
apiVersion: v1
kind: Service
metadata:
  name: adguard-tcp
  annotations:
    metallb.universe.tf/allow-shared-ip: adguard
spec:
  type: LoadBalancer
  selector:
    app: adguard
  ports:
    - name: dns-tcp
      protocol: TCP
      port: 53
      targetPort: dns-tcp
    - name: web
      protocol: TCP
      port: 80
      targetPort: web
    - name: web-setup
      protocol: TCP
      port: 3000
      targetPort: web-setup
  loadBalancerIP: {{ .Values.service.loadBalancerIP }}
  externalTrafficPolicy: Local
---
apiVersion: v1
kind: Service
metadata:
  name: adguard-udp
  annotations:
    metallb.universe.tf/allow-shared-ip: adguard
spec:
  type: LoadBalancer
  selector:
    app: adguard
  ports:
    - name: dns-udp
      protocol: UDP
      port: 53
      targetPort: dns-udp
  loadBalancerIP: {{ .Values.service.loadBalancerIP }}
  externalTrafficPolicy: Local
---
