apiVersion: v1
kind: Service
metadata:
  name: seerr
spec:
  type: {{ .Values.service.type }}
  selector:
    app: seerr
  ports:
  - name: web
    protocol: TCP
    port: {{ .Values.service.port }}
    targetPort: web
